// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/proto/common/java/LocationData.proto

package com.wn.protocol.common;

public final class LCLocationData {
  private LCLocationData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocationDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocationData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 alarm = 1;</code>
     */
    long getAlarm();

    /**
     * <code>int64 status = 2;</code>
     */
    long getStatus();

    /**
     * <code>int32 longitude = 3;</code>
     */
    int getLongitude();

    /**
     * <code>int32 latitude = 4;</code>
     */
    int getLatitude();

    /**
     * <code>int32 originalLng = 5;</code>
     */
    int getOriginalLng();

    /**
     * <code>int32 originalLat = 6;</code>
     */
    int getOriginalLat();

    /**
     * <code>int32 height = 7;</code>
     */
    int getHeight();

    /**
     * <code>int32 speed = 8;</code>
     */
    int getSpeed();

    /**
     * <code>int32 direction = 9;</code>
     */
    int getDirection();

    /**
     * <code>int64 gpsDate = 10;</code>
     */
    long getGpsDate();

    /**
     * <code>int64 mileage = 11;</code>
     */
    long getMileage();

    /**
     * <code>int64 receiveDate = 12;</code>
     */
    long getReceiveDate();

    /**
     * <code>bool isPatch = 13;</code>
     */
    boolean getIsPatch();

    /**
     * <code>int32 oil = 14;</code>
     */
    int getOil();

    /**
     * <code>int32 recorderSpeed = 15;</code>
     */
    int getRecorderSpeed();

    /**
     * <code>int32 starStatus = 20;</code>
     */
    int getStarStatus();

    /**
     * <code>int32 starNumber = 21;</code>
     */
    int getStarNumber();

    /**
     * <code>int32 alarmIdentify = 22;</code>
     */
    int getAlarmIdentify();

    /**
     * <code>int32 signalStatus = 23;</code>
     */
    int getSignalStatus();

    /**
     * <code>int32 ioStatus = 24;</code>
     */
    int getIoStatus();

    /**
     * <code>int32 analogAD0 = 25;</code>
     */
    int getAnalogAD0();

    /**
     * <code>int32 analogAD1 = 26;</code>
     */
    int getAnalogAD1();

    /**
     * <code>int32 signalStrength = 27;</code>
     */
    int getSignalStrength();

    /**
     * <code>int32 satelliteNumber = 28;</code>
     */
    int getSatelliteNumber();

    /**
     * <code>bool isValid = 29;</code>
     */
    boolean getIsValid();

    /**
     * <code>bytes additionAlarm = 34;</code>
     */
    com.google.protobuf.ByteString getAdditionAlarm();

    /**
     * <pre>
     *repeated ???????list
     * </pre>
     *
     * <code>repeated int32 noList = 35;</code>
     */
    java.util.List<java.lang.Integer> getNoListList();
    /**
     * <pre>
     *repeated ???????list
     * </pre>
     *
     * <code>repeated int32 noList = 35;</code>
     */
    int getNoListCount();
    /**
     * <pre>
     *repeated ???????list
     * </pre>
     *
     * <code>repeated int32 noList = 35;</code>
     */
    int getNoList(int index);
  }
  /**
   * Protobuf type {@code LocationData}
   */
  public  static final class LocationData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocationData)
      LocationDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocationData.newBuilder() to construct.
    private LocationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocationData() {
      alarm_ = 0L;
      status_ = 0L;
      longitude_ = 0;
      latitude_ = 0;
      originalLng_ = 0;
      originalLat_ = 0;
      height_ = 0;
      speed_ = 0;
      direction_ = 0;
      gpsDate_ = 0L;
      mileage_ = 0L;
      receiveDate_ = 0L;
      isPatch_ = false;
      oil_ = 0;
      recorderSpeed_ = 0;
      starStatus_ = 0;
      starNumber_ = 0;
      alarmIdentify_ = 0;
      signalStatus_ = 0;
      ioStatus_ = 0;
      analogAD0_ = 0;
      analogAD1_ = 0;
      signalStrength_ = 0;
      satelliteNumber_ = 0;
      isValid_ = false;
      additionAlarm_ = com.google.protobuf.ByteString.EMPTY;
      noList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocationData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              alarm_ = input.readInt64();
              break;
            }
            case 16: {

              status_ = input.readInt64();
              break;
            }
            case 24: {

              longitude_ = input.readInt32();
              break;
            }
            case 32: {

              latitude_ = input.readInt32();
              break;
            }
            case 40: {

              originalLng_ = input.readInt32();
              break;
            }
            case 48: {

              originalLat_ = input.readInt32();
              break;
            }
            case 56: {

              height_ = input.readInt32();
              break;
            }
            case 64: {

              speed_ = input.readInt32();
              break;
            }
            case 72: {

              direction_ = input.readInt32();
              break;
            }
            case 80: {

              gpsDate_ = input.readInt64();
              break;
            }
            case 88: {

              mileage_ = input.readInt64();
              break;
            }
            case 96: {

              receiveDate_ = input.readInt64();
              break;
            }
            case 104: {

              isPatch_ = input.readBool();
              break;
            }
            case 112: {

              oil_ = input.readInt32();
              break;
            }
            case 120: {

              recorderSpeed_ = input.readInt32();
              break;
            }
            case 160: {

              starStatus_ = input.readInt32();
              break;
            }
            case 168: {

              starNumber_ = input.readInt32();
              break;
            }
            case 176: {

              alarmIdentify_ = input.readInt32();
              break;
            }
            case 184: {

              signalStatus_ = input.readInt32();
              break;
            }
            case 192: {

              ioStatus_ = input.readInt32();
              break;
            }
            case 200: {

              analogAD0_ = input.readInt32();
              break;
            }
            case 208: {

              analogAD1_ = input.readInt32();
              break;
            }
            case 216: {

              signalStrength_ = input.readInt32();
              break;
            }
            case 224: {

              satelliteNumber_ = input.readInt32();
              break;
            }
            case 232: {

              isValid_ = input.readBool();
              break;
            }
            case 274: {

              additionAlarm_ = input.readBytes();
              break;
            }
            case 280: {
              if (!((mutable_bitField0_ & 0x04000000) == 0x04000000)) {
                noList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x04000000;
              }
              noList_.add(input.readInt32());
              break;
            }
            case 282: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x04000000) == 0x04000000) && input.getBytesUntilLimit() > 0) {
                noList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x04000000;
              }
              while (input.getBytesUntilLimit() > 0) {
                noList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x04000000) == 0x04000000)) {
          noList_ = java.util.Collections.unmodifiableList(noList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wn.protocol.common.LCLocationData.internal_static_LocationData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wn.protocol.common.LCLocationData.internal_static_LocationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wn.protocol.common.LCLocationData.LocationData.class, com.wn.protocol.common.LCLocationData.LocationData.Builder.class);
    }

    private int bitField0_;
    public static final int ALARM_FIELD_NUMBER = 1;
    private long alarm_;
    /**
     * <code>int64 alarm = 1;</code>
     */
    public long getAlarm() {
      return alarm_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private long status_;
    /**
     * <code>int64 status = 2;</code>
     */
    public long getStatus() {
      return status_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private int longitude_;
    /**
     * <code>int32 longitude = 3;</code>
     */
    public int getLongitude() {
      return longitude_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 4;
    private int latitude_;
    /**
     * <code>int32 latitude = 4;</code>
     */
    public int getLatitude() {
      return latitude_;
    }

    public static final int ORIGINALLNG_FIELD_NUMBER = 5;
    private int originalLng_;
    /**
     * <code>int32 originalLng = 5;</code>
     */
    public int getOriginalLng() {
      return originalLng_;
    }

    public static final int ORIGINALLAT_FIELD_NUMBER = 6;
    private int originalLat_;
    /**
     * <code>int32 originalLat = 6;</code>
     */
    public int getOriginalLat() {
      return originalLat_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 7;
    private int height_;
    /**
     * <code>int32 height = 7;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int SPEED_FIELD_NUMBER = 8;
    private int speed_;
    /**
     * <code>int32 speed = 8;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 9;
    private int direction_;
    /**
     * <code>int32 direction = 9;</code>
     */
    public int getDirection() {
      return direction_;
    }

    public static final int GPSDATE_FIELD_NUMBER = 10;
    private long gpsDate_;
    /**
     * <code>int64 gpsDate = 10;</code>
     */
    public long getGpsDate() {
      return gpsDate_;
    }

    public static final int MILEAGE_FIELD_NUMBER = 11;
    private long mileage_;
    /**
     * <code>int64 mileage = 11;</code>
     */
    public long getMileage() {
      return mileage_;
    }

    public static final int RECEIVEDATE_FIELD_NUMBER = 12;
    private long receiveDate_;
    /**
     * <code>int64 receiveDate = 12;</code>
     */
    public long getReceiveDate() {
      return receiveDate_;
    }

    public static final int ISPATCH_FIELD_NUMBER = 13;
    private boolean isPatch_;
    /**
     * <code>bool isPatch = 13;</code>
     */
    public boolean getIsPatch() {
      return isPatch_;
    }

    public static final int OIL_FIELD_NUMBER = 14;
    private int oil_;
    /**
     * <code>int32 oil = 14;</code>
     */
    public int getOil() {
      return oil_;
    }

    public static final int RECORDERSPEED_FIELD_NUMBER = 15;
    private int recorderSpeed_;
    /**
     * <code>int32 recorderSpeed = 15;</code>
     */
    public int getRecorderSpeed() {
      return recorderSpeed_;
    }

    public static final int STARSTATUS_FIELD_NUMBER = 20;
    private int starStatus_;
    /**
     * <code>int32 starStatus = 20;</code>
     */
    public int getStarStatus() {
      return starStatus_;
    }

    public static final int STARNUMBER_FIELD_NUMBER = 21;
    private int starNumber_;
    /**
     * <code>int32 starNumber = 21;</code>
     */
    public int getStarNumber() {
      return starNumber_;
    }

    public static final int ALARMIDENTIFY_FIELD_NUMBER = 22;
    private int alarmIdentify_;
    /**
     * <code>int32 alarmIdentify = 22;</code>
     */
    public int getAlarmIdentify() {
      return alarmIdentify_;
    }

    public static final int SIGNALSTATUS_FIELD_NUMBER = 23;
    private int signalStatus_;
    /**
     * <code>int32 signalStatus = 23;</code>
     */
    public int getSignalStatus() {
      return signalStatus_;
    }

    public static final int IOSTATUS_FIELD_NUMBER = 24;
    private int ioStatus_;
    /**
     * <code>int32 ioStatus = 24;</code>
     */
    public int getIoStatus() {
      return ioStatus_;
    }

    public static final int ANALOGAD0_FIELD_NUMBER = 25;
    private int analogAD0_;
    /**
     * <code>int32 analogAD0 = 25;</code>
     */
    public int getAnalogAD0() {
      return analogAD0_;
    }

    public static final int ANALOGAD1_FIELD_NUMBER = 26;
    private int analogAD1_;
    /**
     * <code>int32 analogAD1 = 26;</code>
     */
    public int getAnalogAD1() {
      return analogAD1_;
    }

    public static final int SIGNALSTRENGTH_FIELD_NUMBER = 27;
    private int signalStrength_;
    /**
     * <code>int32 signalStrength = 27;</code>
     */
    public int getSignalStrength() {
      return signalStrength_;
    }

    public static final int SATELLITENUMBER_FIELD_NUMBER = 28;
    private int satelliteNumber_;
    /**
     * <code>int32 satelliteNumber = 28;</code>
     */
    public int getSatelliteNumber() {
      return satelliteNumber_;
    }

    public static final int ISVALID_FIELD_NUMBER = 29;
    private boolean isValid_;
    /**
     * <code>bool isValid = 29;</code>
     */
    public boolean getIsValid() {
      return isValid_;
    }

    public static final int ADDITIONALARM_FIELD_NUMBER = 34;
    private com.google.protobuf.ByteString additionAlarm_;
    /**
     * <code>bytes additionAlarm = 34;</code>
     */
    public com.google.protobuf.ByteString getAdditionAlarm() {
      return additionAlarm_;
    }

    public static final int NOLIST_FIELD_NUMBER = 35;
    private java.util.List<java.lang.Integer> noList_;
    /**
     * <pre>
     *repeated ???????list
     * </pre>
     *
     * <code>repeated int32 noList = 35;</code>
     */
    public java.util.List<java.lang.Integer>
        getNoListList() {
      return noList_;
    }
    /**
     * <pre>
     *repeated ???????list
     * </pre>
     *
     * <code>repeated int32 noList = 35;</code>
     */
    public int getNoListCount() {
      return noList_.size();
    }
    /**
     * <pre>
     *repeated ???????list
     * </pre>
     *
     * <code>repeated int32 noList = 35;</code>
     */
    public int getNoList(int index) {
      return noList_.get(index);
    }
    private int noListMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (alarm_ != 0L) {
        output.writeInt64(1, alarm_);
      }
      if (status_ != 0L) {
        output.writeInt64(2, status_);
      }
      if (longitude_ != 0) {
        output.writeInt32(3, longitude_);
      }
      if (latitude_ != 0) {
        output.writeInt32(4, latitude_);
      }
      if (originalLng_ != 0) {
        output.writeInt32(5, originalLng_);
      }
      if (originalLat_ != 0) {
        output.writeInt32(6, originalLat_);
      }
      if (height_ != 0) {
        output.writeInt32(7, height_);
      }
      if (speed_ != 0) {
        output.writeInt32(8, speed_);
      }
      if (direction_ != 0) {
        output.writeInt32(9, direction_);
      }
      if (gpsDate_ != 0L) {
        output.writeInt64(10, gpsDate_);
      }
      if (mileage_ != 0L) {
        output.writeInt64(11, mileage_);
      }
      if (receiveDate_ != 0L) {
        output.writeInt64(12, receiveDate_);
      }
      if (isPatch_ != false) {
        output.writeBool(13, isPatch_);
      }
      if (oil_ != 0) {
        output.writeInt32(14, oil_);
      }
      if (recorderSpeed_ != 0) {
        output.writeInt32(15, recorderSpeed_);
      }
      if (starStatus_ != 0) {
        output.writeInt32(20, starStatus_);
      }
      if (starNumber_ != 0) {
        output.writeInt32(21, starNumber_);
      }
      if (alarmIdentify_ != 0) {
        output.writeInt32(22, alarmIdentify_);
      }
      if (signalStatus_ != 0) {
        output.writeInt32(23, signalStatus_);
      }
      if (ioStatus_ != 0) {
        output.writeInt32(24, ioStatus_);
      }
      if (analogAD0_ != 0) {
        output.writeInt32(25, analogAD0_);
      }
      if (analogAD1_ != 0) {
        output.writeInt32(26, analogAD1_);
      }
      if (signalStrength_ != 0) {
        output.writeInt32(27, signalStrength_);
      }
      if (satelliteNumber_ != 0) {
        output.writeInt32(28, satelliteNumber_);
      }
      if (isValid_ != false) {
        output.writeBool(29, isValid_);
      }
      if (!additionAlarm_.isEmpty()) {
        output.writeBytes(34, additionAlarm_);
      }
      if (getNoListList().size() > 0) {
        output.writeUInt32NoTag(282);
        output.writeUInt32NoTag(noListMemoizedSerializedSize);
      }
      for (int i = 0; i < noList_.size(); i++) {
        output.writeInt32NoTag(noList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (alarm_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, alarm_);
      }
      if (status_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, status_);
      }
      if (longitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, longitude_);
      }
      if (latitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, latitude_);
      }
      if (originalLng_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, originalLng_);
      }
      if (originalLat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, originalLat_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, height_);
      }
      if (speed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, speed_);
      }
      if (direction_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, direction_);
      }
      if (gpsDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, gpsDate_);
      }
      if (mileage_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, mileage_);
      }
      if (receiveDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, receiveDate_);
      }
      if (isPatch_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, isPatch_);
      }
      if (oil_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, oil_);
      }
      if (recorderSpeed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, recorderSpeed_);
      }
      if (starStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, starStatus_);
      }
      if (starNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, starNumber_);
      }
      if (alarmIdentify_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, alarmIdentify_);
      }
      if (signalStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, signalStatus_);
      }
      if (ioStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(24, ioStatus_);
      }
      if (analogAD0_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(25, analogAD0_);
      }
      if (analogAD1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(26, analogAD1_);
      }
      if (signalStrength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(27, signalStrength_);
      }
      if (satelliteNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(28, satelliteNumber_);
      }
      if (isValid_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(29, isValid_);
      }
      if (!additionAlarm_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(34, additionAlarm_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < noList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(noList_.get(i));
        }
        size += dataSize;
        if (!getNoListList().isEmpty()) {
          size += 2;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        noListMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wn.protocol.common.LCLocationData.LocationData)) {
        return super.equals(obj);
      }
      com.wn.protocol.common.LCLocationData.LocationData other = (com.wn.protocol.common.LCLocationData.LocationData) obj;

      boolean result = true;
      result = result && (getAlarm()
          == other.getAlarm());
      result = result && (getStatus()
          == other.getStatus());
      result = result && (getLongitude()
          == other.getLongitude());
      result = result && (getLatitude()
          == other.getLatitude());
      result = result && (getOriginalLng()
          == other.getOriginalLng());
      result = result && (getOriginalLat()
          == other.getOriginalLat());
      result = result && (getHeight()
          == other.getHeight());
      result = result && (getSpeed()
          == other.getSpeed());
      result = result && (getDirection()
          == other.getDirection());
      result = result && (getGpsDate()
          == other.getGpsDate());
      result = result && (getMileage()
          == other.getMileage());
      result = result && (getReceiveDate()
          == other.getReceiveDate());
      result = result && (getIsPatch()
          == other.getIsPatch());
      result = result && (getOil()
          == other.getOil());
      result = result && (getRecorderSpeed()
          == other.getRecorderSpeed());
      result = result && (getStarStatus()
          == other.getStarStatus());
      result = result && (getStarNumber()
          == other.getStarNumber());
      result = result && (getAlarmIdentify()
          == other.getAlarmIdentify());
      result = result && (getSignalStatus()
          == other.getSignalStatus());
      result = result && (getIoStatus()
          == other.getIoStatus());
      result = result && (getAnalogAD0()
          == other.getAnalogAD0());
      result = result && (getAnalogAD1()
          == other.getAnalogAD1());
      result = result && (getSignalStrength()
          == other.getSignalStrength());
      result = result && (getSatelliteNumber()
          == other.getSatelliteNumber());
      result = result && (getIsValid()
          == other.getIsValid());
      result = result && getAdditionAlarm()
          .equals(other.getAdditionAlarm());
      result = result && getNoListList()
          .equals(other.getNoListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ALARM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAlarm());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatus());
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLongitude();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLatitude();
      hash = (37 * hash) + ORIGINALLNG_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalLng();
      hash = (37 * hash) + ORIGINALLAT_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalLat();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + getSpeed();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection();
      hash = (37 * hash) + GPSDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGpsDate());
      hash = (37 * hash) + MILEAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMileage());
      hash = (37 * hash) + RECEIVEDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiveDate());
      hash = (37 * hash) + ISPATCH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsPatch());
      hash = (37 * hash) + OIL_FIELD_NUMBER;
      hash = (53 * hash) + getOil();
      hash = (37 * hash) + RECORDERSPEED_FIELD_NUMBER;
      hash = (53 * hash) + getRecorderSpeed();
      hash = (37 * hash) + STARSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStarStatus();
      hash = (37 * hash) + STARNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getStarNumber();
      hash = (37 * hash) + ALARMIDENTIFY_FIELD_NUMBER;
      hash = (53 * hash) + getAlarmIdentify();
      hash = (37 * hash) + SIGNALSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getSignalStatus();
      hash = (37 * hash) + IOSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getIoStatus();
      hash = (37 * hash) + ANALOGAD0_FIELD_NUMBER;
      hash = (53 * hash) + getAnalogAD0();
      hash = (37 * hash) + ANALOGAD1_FIELD_NUMBER;
      hash = (53 * hash) + getAnalogAD1();
      hash = (37 * hash) + SIGNALSTRENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getSignalStrength();
      hash = (37 * hash) + SATELLITENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSatelliteNumber();
      hash = (37 * hash) + ISVALID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsValid());
      hash = (37 * hash) + ADDITIONALARM_FIELD_NUMBER;
      hash = (53 * hash) + getAdditionAlarm().hashCode();
      if (getNoListCount() > 0) {
        hash = (37 * hash) + NOLIST_FIELD_NUMBER;
        hash = (53 * hash) + getNoListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wn.protocol.common.LCLocationData.LocationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wn.protocol.common.LCLocationData.LocationData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocationData)
        com.wn.protocol.common.LCLocationData.LocationDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wn.protocol.common.LCLocationData.internal_static_LocationData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wn.protocol.common.LCLocationData.internal_static_LocationData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wn.protocol.common.LCLocationData.LocationData.class, com.wn.protocol.common.LCLocationData.LocationData.Builder.class);
      }

      // Construct using com.wn.protocol.common.LCLocationData.LocationData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        alarm_ = 0L;

        status_ = 0L;

        longitude_ = 0;

        latitude_ = 0;

        originalLng_ = 0;

        originalLat_ = 0;

        height_ = 0;

        speed_ = 0;

        direction_ = 0;

        gpsDate_ = 0L;

        mileage_ = 0L;

        receiveDate_ = 0L;

        isPatch_ = false;

        oil_ = 0;

        recorderSpeed_ = 0;

        starStatus_ = 0;

        starNumber_ = 0;

        alarmIdentify_ = 0;

        signalStatus_ = 0;

        ioStatus_ = 0;

        analogAD0_ = 0;

        analogAD1_ = 0;

        signalStrength_ = 0;

        satelliteNumber_ = 0;

        isValid_ = false;

        additionAlarm_ = com.google.protobuf.ByteString.EMPTY;

        noList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x04000000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wn.protocol.common.LCLocationData.internal_static_LocationData_descriptor;
      }

      public com.wn.protocol.common.LCLocationData.LocationData getDefaultInstanceForType() {
        return com.wn.protocol.common.LCLocationData.LocationData.getDefaultInstance();
      }

      public com.wn.protocol.common.LCLocationData.LocationData build() {
        com.wn.protocol.common.LCLocationData.LocationData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wn.protocol.common.LCLocationData.LocationData buildPartial() {
        com.wn.protocol.common.LCLocationData.LocationData result = new com.wn.protocol.common.LCLocationData.LocationData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.alarm_ = alarm_;
        result.status_ = status_;
        result.longitude_ = longitude_;
        result.latitude_ = latitude_;
        result.originalLng_ = originalLng_;
        result.originalLat_ = originalLat_;
        result.height_ = height_;
        result.speed_ = speed_;
        result.direction_ = direction_;
        result.gpsDate_ = gpsDate_;
        result.mileage_ = mileage_;
        result.receiveDate_ = receiveDate_;
        result.isPatch_ = isPatch_;
        result.oil_ = oil_;
        result.recorderSpeed_ = recorderSpeed_;
        result.starStatus_ = starStatus_;
        result.starNumber_ = starNumber_;
        result.alarmIdentify_ = alarmIdentify_;
        result.signalStatus_ = signalStatus_;
        result.ioStatus_ = ioStatus_;
        result.analogAD0_ = analogAD0_;
        result.analogAD1_ = analogAD1_;
        result.signalStrength_ = signalStrength_;
        result.satelliteNumber_ = satelliteNumber_;
        result.isValid_ = isValid_;
        result.additionAlarm_ = additionAlarm_;
        if (((bitField0_ & 0x04000000) == 0x04000000)) {
          noList_ = java.util.Collections.unmodifiableList(noList_);
          bitField0_ = (bitField0_ & ~0x04000000);
        }
        result.noList_ = noList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wn.protocol.common.LCLocationData.LocationData) {
          return mergeFrom((com.wn.protocol.common.LCLocationData.LocationData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wn.protocol.common.LCLocationData.LocationData other) {
        if (other == com.wn.protocol.common.LCLocationData.LocationData.getDefaultInstance()) return this;
        if (other.getAlarm() != 0L) {
          setAlarm(other.getAlarm());
        }
        if (other.getStatus() != 0L) {
          setStatus(other.getStatus());
        }
        if (other.getLongitude() != 0) {
          setLongitude(other.getLongitude());
        }
        if (other.getLatitude() != 0) {
          setLatitude(other.getLatitude());
        }
        if (other.getOriginalLng() != 0) {
          setOriginalLng(other.getOriginalLng());
        }
        if (other.getOriginalLat() != 0) {
          setOriginalLat(other.getOriginalLat());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getSpeed() != 0) {
          setSpeed(other.getSpeed());
        }
        if (other.getDirection() != 0) {
          setDirection(other.getDirection());
        }
        if (other.getGpsDate() != 0L) {
          setGpsDate(other.getGpsDate());
        }
        if (other.getMileage() != 0L) {
          setMileage(other.getMileage());
        }
        if (other.getReceiveDate() != 0L) {
          setReceiveDate(other.getReceiveDate());
        }
        if (other.getIsPatch() != false) {
          setIsPatch(other.getIsPatch());
        }
        if (other.getOil() != 0) {
          setOil(other.getOil());
        }
        if (other.getRecorderSpeed() != 0) {
          setRecorderSpeed(other.getRecorderSpeed());
        }
        if (other.getStarStatus() != 0) {
          setStarStatus(other.getStarStatus());
        }
        if (other.getStarNumber() != 0) {
          setStarNumber(other.getStarNumber());
        }
        if (other.getAlarmIdentify() != 0) {
          setAlarmIdentify(other.getAlarmIdentify());
        }
        if (other.getSignalStatus() != 0) {
          setSignalStatus(other.getSignalStatus());
        }
        if (other.getIoStatus() != 0) {
          setIoStatus(other.getIoStatus());
        }
        if (other.getAnalogAD0() != 0) {
          setAnalogAD0(other.getAnalogAD0());
        }
        if (other.getAnalogAD1() != 0) {
          setAnalogAD1(other.getAnalogAD1());
        }
        if (other.getSignalStrength() != 0) {
          setSignalStrength(other.getSignalStrength());
        }
        if (other.getSatelliteNumber() != 0) {
          setSatelliteNumber(other.getSatelliteNumber());
        }
        if (other.getIsValid() != false) {
          setIsValid(other.getIsValid());
        }
        if (other.getAdditionAlarm() != com.google.protobuf.ByteString.EMPTY) {
          setAdditionAlarm(other.getAdditionAlarm());
        }
        if (!other.noList_.isEmpty()) {
          if (noList_.isEmpty()) {
            noList_ = other.noList_;
            bitField0_ = (bitField0_ & ~0x04000000);
          } else {
            ensureNoListIsMutable();
            noList_.addAll(other.noList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wn.protocol.common.LCLocationData.LocationData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wn.protocol.common.LCLocationData.LocationData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long alarm_ ;
      /**
       * <code>int64 alarm = 1;</code>
       */
      public long getAlarm() {
        return alarm_;
      }
      /**
       * <code>int64 alarm = 1;</code>
       */
      public Builder setAlarm(long value) {
        
        alarm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 alarm = 1;</code>
       */
      public Builder clearAlarm() {
        
        alarm_ = 0L;
        onChanged();
        return this;
      }

      private long status_ ;
      /**
       * <code>int64 status = 2;</code>
       */
      public long getStatus() {
        return status_;
      }
      /**
       * <code>int64 status = 2;</code>
       */
      public Builder setStatus(long value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0L;
        onChanged();
        return this;
      }

      private int longitude_ ;
      /**
       * <code>int32 longitude = 3;</code>
       */
      public int getLongitude() {
        return longitude_;
      }
      /**
       * <code>int32 longitude = 3;</code>
       */
      public Builder setLongitude(int value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 longitude = 3;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0;
        onChanged();
        return this;
      }

      private int latitude_ ;
      /**
       * <code>int32 latitude = 4;</code>
       */
      public int getLatitude() {
        return latitude_;
      }
      /**
       * <code>int32 latitude = 4;</code>
       */
      public Builder setLatitude(int value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 latitude = 4;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0;
        onChanged();
        return this;
      }

      private int originalLng_ ;
      /**
       * <code>int32 originalLng = 5;</code>
       */
      public int getOriginalLng() {
        return originalLng_;
      }
      /**
       * <code>int32 originalLng = 5;</code>
       */
      public Builder setOriginalLng(int value) {
        
        originalLng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 originalLng = 5;</code>
       */
      public Builder clearOriginalLng() {
        
        originalLng_ = 0;
        onChanged();
        return this;
      }

      private int originalLat_ ;
      /**
       * <code>int32 originalLat = 6;</code>
       */
      public int getOriginalLat() {
        return originalLat_;
      }
      /**
       * <code>int32 originalLat = 6;</code>
       */
      public Builder setOriginalLat(int value) {
        
        originalLat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 originalLat = 6;</code>
       */
      public Builder clearOriginalLat() {
        
        originalLat_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 7;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 7;</code>
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 7;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <code>int32 speed = 8;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>int32 speed = 8;</code>
       */
      public Builder setSpeed(int value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 speed = 8;</code>
       */
      public Builder clearSpeed() {
        
        speed_ = 0;
        onChanged();
        return this;
      }

      private int direction_ ;
      /**
       * <code>int32 direction = 9;</code>
       */
      public int getDirection() {
        return direction_;
      }
      /**
       * <code>int32 direction = 9;</code>
       */
      public Builder setDirection(int value) {
        
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 direction = 9;</code>
       */
      public Builder clearDirection() {
        
        direction_ = 0;
        onChanged();
        return this;
      }

      private long gpsDate_ ;
      /**
       * <code>int64 gpsDate = 10;</code>
       */
      public long getGpsDate() {
        return gpsDate_;
      }
      /**
       * <code>int64 gpsDate = 10;</code>
       */
      public Builder setGpsDate(long value) {
        
        gpsDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 gpsDate = 10;</code>
       */
      public Builder clearGpsDate() {
        
        gpsDate_ = 0L;
        onChanged();
        return this;
      }

      private long mileage_ ;
      /**
       * <code>int64 mileage = 11;</code>
       */
      public long getMileage() {
        return mileage_;
      }
      /**
       * <code>int64 mileage = 11;</code>
       */
      public Builder setMileage(long value) {
        
        mileage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 mileage = 11;</code>
       */
      public Builder clearMileage() {
        
        mileage_ = 0L;
        onChanged();
        return this;
      }

      private long receiveDate_ ;
      /**
       * <code>int64 receiveDate = 12;</code>
       */
      public long getReceiveDate() {
        return receiveDate_;
      }
      /**
       * <code>int64 receiveDate = 12;</code>
       */
      public Builder setReceiveDate(long value) {
        
        receiveDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 receiveDate = 12;</code>
       */
      public Builder clearReceiveDate() {
        
        receiveDate_ = 0L;
        onChanged();
        return this;
      }

      private boolean isPatch_ ;
      /**
       * <code>bool isPatch = 13;</code>
       */
      public boolean getIsPatch() {
        return isPatch_;
      }
      /**
       * <code>bool isPatch = 13;</code>
       */
      public Builder setIsPatch(boolean value) {
        
        isPatch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isPatch = 13;</code>
       */
      public Builder clearIsPatch() {
        
        isPatch_ = false;
        onChanged();
        return this;
      }

      private int oil_ ;
      /**
       * <code>int32 oil = 14;</code>
       */
      public int getOil() {
        return oil_;
      }
      /**
       * <code>int32 oil = 14;</code>
       */
      public Builder setOil(int value) {
        
        oil_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 oil = 14;</code>
       */
      public Builder clearOil() {
        
        oil_ = 0;
        onChanged();
        return this;
      }

      private int recorderSpeed_ ;
      /**
       * <code>int32 recorderSpeed = 15;</code>
       */
      public int getRecorderSpeed() {
        return recorderSpeed_;
      }
      /**
       * <code>int32 recorderSpeed = 15;</code>
       */
      public Builder setRecorderSpeed(int value) {
        
        recorderSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 recorderSpeed = 15;</code>
       */
      public Builder clearRecorderSpeed() {
        
        recorderSpeed_ = 0;
        onChanged();
        return this;
      }

      private int starStatus_ ;
      /**
       * <code>int32 starStatus = 20;</code>
       */
      public int getStarStatus() {
        return starStatus_;
      }
      /**
       * <code>int32 starStatus = 20;</code>
       */
      public Builder setStarStatus(int value) {
        
        starStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 starStatus = 20;</code>
       */
      public Builder clearStarStatus() {
        
        starStatus_ = 0;
        onChanged();
        return this;
      }

      private int starNumber_ ;
      /**
       * <code>int32 starNumber = 21;</code>
       */
      public int getStarNumber() {
        return starNumber_;
      }
      /**
       * <code>int32 starNumber = 21;</code>
       */
      public Builder setStarNumber(int value) {
        
        starNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 starNumber = 21;</code>
       */
      public Builder clearStarNumber() {
        
        starNumber_ = 0;
        onChanged();
        return this;
      }

      private int alarmIdentify_ ;
      /**
       * <code>int32 alarmIdentify = 22;</code>
       */
      public int getAlarmIdentify() {
        return alarmIdentify_;
      }
      /**
       * <code>int32 alarmIdentify = 22;</code>
       */
      public Builder setAlarmIdentify(int value) {
        
        alarmIdentify_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 alarmIdentify = 22;</code>
       */
      public Builder clearAlarmIdentify() {
        
        alarmIdentify_ = 0;
        onChanged();
        return this;
      }

      private int signalStatus_ ;
      /**
       * <code>int32 signalStatus = 23;</code>
       */
      public int getSignalStatus() {
        return signalStatus_;
      }
      /**
       * <code>int32 signalStatus = 23;</code>
       */
      public Builder setSignalStatus(int value) {
        
        signalStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 signalStatus = 23;</code>
       */
      public Builder clearSignalStatus() {
        
        signalStatus_ = 0;
        onChanged();
        return this;
      }

      private int ioStatus_ ;
      /**
       * <code>int32 ioStatus = 24;</code>
       */
      public int getIoStatus() {
        return ioStatus_;
      }
      /**
       * <code>int32 ioStatus = 24;</code>
       */
      public Builder setIoStatus(int value) {
        
        ioStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ioStatus = 24;</code>
       */
      public Builder clearIoStatus() {
        
        ioStatus_ = 0;
        onChanged();
        return this;
      }

      private int analogAD0_ ;
      /**
       * <code>int32 analogAD0 = 25;</code>
       */
      public int getAnalogAD0() {
        return analogAD0_;
      }
      /**
       * <code>int32 analogAD0 = 25;</code>
       */
      public Builder setAnalogAD0(int value) {
        
        analogAD0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 analogAD0 = 25;</code>
       */
      public Builder clearAnalogAD0() {
        
        analogAD0_ = 0;
        onChanged();
        return this;
      }

      private int analogAD1_ ;
      /**
       * <code>int32 analogAD1 = 26;</code>
       */
      public int getAnalogAD1() {
        return analogAD1_;
      }
      /**
       * <code>int32 analogAD1 = 26;</code>
       */
      public Builder setAnalogAD1(int value) {
        
        analogAD1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 analogAD1 = 26;</code>
       */
      public Builder clearAnalogAD1() {
        
        analogAD1_ = 0;
        onChanged();
        return this;
      }

      private int signalStrength_ ;
      /**
       * <code>int32 signalStrength = 27;</code>
       */
      public int getSignalStrength() {
        return signalStrength_;
      }
      /**
       * <code>int32 signalStrength = 27;</code>
       */
      public Builder setSignalStrength(int value) {
        
        signalStrength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 signalStrength = 27;</code>
       */
      public Builder clearSignalStrength() {
        
        signalStrength_ = 0;
        onChanged();
        return this;
      }

      private int satelliteNumber_ ;
      /**
       * <code>int32 satelliteNumber = 28;</code>
       */
      public int getSatelliteNumber() {
        return satelliteNumber_;
      }
      /**
       * <code>int32 satelliteNumber = 28;</code>
       */
      public Builder setSatelliteNumber(int value) {
        
        satelliteNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 satelliteNumber = 28;</code>
       */
      public Builder clearSatelliteNumber() {
        
        satelliteNumber_ = 0;
        onChanged();
        return this;
      }

      private boolean isValid_ ;
      /**
       * <code>bool isValid = 29;</code>
       */
      public boolean getIsValid() {
        return isValid_;
      }
      /**
       * <code>bool isValid = 29;</code>
       */
      public Builder setIsValid(boolean value) {
        
        isValid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isValid = 29;</code>
       */
      public Builder clearIsValid() {
        
        isValid_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString additionAlarm_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes additionAlarm = 34;</code>
       */
      public com.google.protobuf.ByteString getAdditionAlarm() {
        return additionAlarm_;
      }
      /**
       * <code>bytes additionAlarm = 34;</code>
       */
      public Builder setAdditionAlarm(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        additionAlarm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes additionAlarm = 34;</code>
       */
      public Builder clearAdditionAlarm() {
        
        additionAlarm_ = getDefaultInstance().getAdditionAlarm();
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> noList_ = java.util.Collections.emptyList();
      private void ensureNoListIsMutable() {
        if (!((bitField0_ & 0x04000000) == 0x04000000)) {
          noList_ = new java.util.ArrayList<java.lang.Integer>(noList_);
          bitField0_ |= 0x04000000;
         }
      }
      /**
       * <pre>
       *repeated ???????list
       * </pre>
       *
       * <code>repeated int32 noList = 35;</code>
       */
      public java.util.List<java.lang.Integer>
          getNoListList() {
        return java.util.Collections.unmodifiableList(noList_);
      }
      /**
       * <pre>
       *repeated ???????list
       * </pre>
       *
       * <code>repeated int32 noList = 35;</code>
       */
      public int getNoListCount() {
        return noList_.size();
      }
      /**
       * <pre>
       *repeated ???????list
       * </pre>
       *
       * <code>repeated int32 noList = 35;</code>
       */
      public int getNoList(int index) {
        return noList_.get(index);
      }
      /**
       * <pre>
       *repeated ???????list
       * </pre>
       *
       * <code>repeated int32 noList = 35;</code>
       */
      public Builder setNoList(
          int index, int value) {
        ensureNoListIsMutable();
        noList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *repeated ???????list
       * </pre>
       *
       * <code>repeated int32 noList = 35;</code>
       */
      public Builder addNoList(int value) {
        ensureNoListIsMutable();
        noList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *repeated ???????list
       * </pre>
       *
       * <code>repeated int32 noList = 35;</code>
       */
      public Builder addAllNoList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureNoListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, noList_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *repeated ???????list
       * </pre>
       *
       * <code>repeated int32 noList = 35;</code>
       */
      public Builder clearNoList() {
        noList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x04000000);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LocationData)
    }

    // @@protoc_insertion_point(class_scope:LocationData)
    private static final com.wn.protocol.common.LCLocationData.LocationData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wn.protocol.common.LCLocationData.LocationData();
    }

    public static com.wn.protocol.common.LCLocationData.LocationData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocationData>
        PARSER = new com.google.protobuf.AbstractParser<LocationData>() {
      public LocationData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LocationData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocationData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocationData> getParserForType() {
      return PARSER;
    }

    public com.wn.protocol.common.LCLocationData.LocationData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)core/proto/common/java/LocationData.pr" +
      "oto\"\220\004\n\014LocationData\022\r\n\005alarm\030\001 \001(\003\022\016\n\006s" +
      "tatus\030\002 \001(\003\022\021\n\tlongitude\030\003 \001(\005\022\020\n\010latitu" +
      "de\030\004 \001(\005\022\023\n\013originalLng\030\005 \001(\005\022\023\n\013origina" +
      "lLat\030\006 \001(\005\022\016\n\006height\030\007 \001(\005\022\r\n\005speed\030\010 \001(" +
      "\005\022\021\n\tdirection\030\t \001(\005\022\017\n\007gpsDate\030\n \001(\003\022\017\n" +
      "\007mileage\030\013 \001(\003\022\023\n\013receiveDate\030\014 \001(\003\022\017\n\007i" +
      "sPatch\030\r \001(\010\022\013\n\003oil\030\016 \001(\005\022\025\n\rrecorderSpe" +
      "ed\030\017 \001(\005\022\022\n\nstarStatus\030\024 \001(\005\022\022\n\nstarNumb" +
      "er\030\025 \001(\005\022\025\n\ralarmIdentify\030\026 \001(\005\022\024\n\014signa",
      "lStatus\030\027 \001(\005\022\020\n\010ioStatus\030\030 \001(\005\022\021\n\tanalo" +
      "gAD0\030\031 \001(\005\022\021\n\tanalogAD1\030\032 \001(\005\022\026\n\016signalS" +
      "trength\030\033 \001(\005\022\027\n\017satelliteNumber\030\034 \001(\005\022\017" +
      "\n\007isValid\030\035 \001(\010\022\025\n\radditionAlarm\030\" \001(\014\022\016" +
      "\n\006noList\030# \003(\005B(\n\026com.wn.protocol.common" +
      "B\016LCLocationDatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LocationData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LocationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationData_descriptor,
        new java.lang.String[] { "Alarm", "Status", "Longitude", "Latitude", "OriginalLng", "OriginalLat", "Height", "Speed", "Direction", "GpsDate", "Mileage", "ReceiveDate", "IsPatch", "Oil", "RecorderSpeed", "StarStatus", "StarNumber", "AlarmIdentify", "SignalStatus", "IoStatus", "AnalogAD0", "AnalogAD1", "SignalStrength", "SatelliteNumber", "IsValid", "AdditionAlarm", "NoList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
